import { makeRng } from "../cards/core/rng.ts";

// Lights Out. Clicking a cell toggles it and its orthogonal neighbours; turn every
// light off. Puzzles are generated by starting from all-off and applying random
// clicks, so they're always solvable (re-clicking the same set is the solution).

export function toggle(grid: number[], size: number, i: number): number[] {
  const g = grid.slice();
  const r = Math.floor(i / size);
  const c = i % size;
  const flip = (rr: number, cc: number) => {
    if (rr >= 0 && rr < size && cc >= 0 && cc < size) g[rr * size + cc] ^= 1;
  };
  flip(r, c);
  flip(r - 1, c);
  flip(r + 1, c);
  flip(r, c - 1);
  flip(r, c + 1);
  return g;
}

export function isSolved(grid: number[]): boolean {
  return grid.every((v) => v === 0);
}

export interface LightsPuzzle {
  size: number;
  grid: number[]; // 1 = on
  solution: number[]; // cell indices that solve it
}

export function generate(seed: number, size = 5, presses = 6): LightsPuzzle {
  const rng = makeRng(seed);
  let grid = new Array(size * size).fill(0);
  const used = new Set<number>();
  while (used.size < presses) used.add(rng.int(size * size));
  for (const i of used) grid = toggle(grid, size, i);
  // guard against the (rare) already-solved board — press one more *unused* cell
  if (isSolved(grid)) {
    for (let i = 0; i < size * size; i++) {
      if (!used.has(i)) { grid = toggle(grid, size, i); used.add(i); break; }
    }
  }
  return { size, grid, solution: [...used] };
}
