import { makeRng, type Rng } from "../cards/core/rng.ts";

// Shikaku. Divide the grid into rectangles, each containing exactly one number,
// which equals that rectangle's area. Generated by tiling the grid with random
// rectangles (always a valid solution) and requiring the clues to be unique.

export interface Puzzle {
  size: number;
  numbers: number[]; // clue per cell, 0 where empty
  solution: number[]; // rect id per cell (the generating tiling)
}

function rectCells(r0: number, c0: number, w: number, h: number, n: number): number[] {
  const cells: number[] = [];
  for (let dr = 0; dr < h; dr++) for (let dc = 0; dc < w; dc++) cells.push((r0 + dr) * n + c0 + dc);
  return cells;
}

function tile(n: number, rng: Rng): number[][] {
  const covered = new Array(n * n).fill(false);
  const rects: number[][] = [];
  for (let i = 0; i < n * n; i++) {
    if (covered[i]) continue;
    const r0 = Math.floor(i / n), c0 = i % n;
    let maxW = 0;
    while (c0 + maxW < n && !covered[r0 * n + c0 + maxW]) maxW++;
    const w = 1 + rng.int(Math.min(maxW, 4));
    let maxH = 0;
    height: while (r0 + maxH < n) {
      for (let k = 0; k < w; k++) if (covered[(r0 + maxH) * n + c0 + k]) break height;
      maxH++;
    }
    const h = 1 + rng.int(Math.min(maxH, 4));
    const cells = rectCells(r0, c0, w, h, n);
    for (const idx of cells) covered[idx] = true;
    rects.push(cells);
  }
  return rects;
}

function rectsForCell(cell: number, area: number, numbers: number[], n: number): number[][] {
  const cr = Math.floor(cell / n), cc = cell % n;
  const out: number[][] = [];
  for (let w = 1; w <= area; w++) {
    if (area % w !== 0) continue;
    const h = area / w;
    if (w > n || h > n) continue;
    for (let r0 = Math.max(0, cr - h + 1); r0 <= Math.min(cr, n - h); r0++) {
      for (let c0 = Math.max(0, cc - w + 1); c0 <= Math.min(cc, n - w); c0++) {
        const cells = rectCells(r0, c0, w, h, n);
        if (cells.every((idx) => numbers[idx] === 0 || idx === cell)) out.push(cells);
      }
    }
  }
  return out;
}

export function countSolutions(p: Puzzle, limit = 2): number {
  const n = p.size;
  const numbered = p.numbers.map((v, i) => (v !== 0 ? i : -1)).filter((i) => i >= 0);
  const cands = numbered.map((cell) => rectsForCell(cell, p.numbers[cell], p.numbers, n));
  const covered = new Array(n * n).fill(false);
  let count = 0;
  let steps = 0;
  let capped = false;
  const rec = (k: number): void => {
    if (count >= limit || capped) return;
    if (++steps > 300000) { capped = true; return; }
    if (k === numbered.length) { count++; return; }
    for (const cells of cands[k]) {
      if (cells.some((idx) => covered[idx])) continue;
      for (const idx of cells) covered[idx] = true;
      rec(k + 1);
      for (const idx of cells) covered[idx] = false;
      if (count >= limit || capped) return;
    }
  };
  rec(0);
  return capped ? limit : count;
}

export function solve(p: Puzzle): number[] | null {
  const n = p.size;
  const numbered = p.numbers.map((v, i) => (v !== 0 ? i : -1)).filter((i) => i >= 0);
  const cands = numbered.map((cell) => rectsForCell(cell, p.numbers[cell], p.numbers, n));
  const assign = new Array(n * n).fill(-1);
  const rec = (k: number): boolean => {
    if (k === numbered.length) return true;
    for (const cells of cands[k]) {
      if (cells.some((idx) => assign[idx] !== -1)) continue;
      for (const idx of cells) assign[idx] = numbered[k];
      if (rec(k + 1)) return true;
      for (const idx of cells) assign[idx] = -1;
    }
    return false;
  };
  return rec(0) ? assign : null;
}

export function generate(seed: number, size = 6): Puzzle {
  const rng = makeRng(seed);
  for (let attempt = 0; attempt < 80; attempt++) {
    const rects = tile(size, rng);
    const numbers = new Array(size * size).fill(0);
    const solution = new Array(size * size).fill(-1);
    rects.forEach((cells, id) => {
      cells.forEach((idx) => (solution[idx] = id));
      numbers[cells[rng.int(cells.length)]] = cells.length;
    });
    const p: Puzzle = { size, numbers, solution };
    if (countSolutions(p, 2) === 1) return p;
  }
  // fallback: all 1×1 rectangles (every cell numbered 1) — trivially unique
  const numbers = new Array(size * size).fill(1);
  const solution = [...Array(size * size).keys()];
  return { size, numbers, solution };
}

/** Validate a player's rect assignment (rectId per cell, -1 = unassigned). */
export function isSolved(assign: number[], p: Puzzle): boolean {
  const n = p.size;
  if (assign.some((v) => v < 0)) return false;
  // group cells by assignment, each group must be a rectangle with exactly one
  // number equal to its area
  const groups = new Map<number, number[]>();
  assign.forEach((id, i) => { const a = groups.get(id) ?? []; a.push(i); groups.set(id, a); });
  for (const cells of groups.values()) {
    const rs = cells.map((i) => Math.floor(i / n));
    const cs = cells.map((i) => i % n);
    const r0 = Math.min(...rs), r1 = Math.max(...rs), c0 = Math.min(...cs), c1 = Math.max(...cs);
    if ((r1 - r0 + 1) * (c1 - c0 + 1) !== cells.length) return false; // not a solid rectangle
    const nums = cells.filter((i) => p.numbers[i] !== 0);
    if (nums.length !== 1 || p.numbers[nums[0]] !== cells.length) return false;
  }
  return true;
}
