// Cowork sync: turning a reviewed game into something another mind can work
// with. The app's own analysis is numeric — it can tell you a move cost you 30%
// of the position, not why you kept making that kind of move. This packages the
// game so an assistant can answer the second question.
//
// Pure string-building plus one download; no network, nothing leaves the device
// unless the user copies it somewhere.

import type { GameRecord } from "./useArchive";
import type { GameReview } from "../review/types";
import { LABEL_META } from "../review/rate";
import { catalogEntry, CATEGORY_LABEL } from "../catalog";

function header(r: GameRecord): string {
  const e = catalogEntry(r.gameId);
  const when = new Date(r.endedISO).toISOString().slice(0, 10);
  return [
    `# ${r.gameName} — ${r.outcome}${r.reason ? ` (${r.reason})` : ""}`,
    "",
    `- **Wing:** ${e ? CATEGORY_LABEL[e.category] : "unknown"}`,
    `- **Played:** ${when}`,
    `- **Opponent:** ${r.opponent}${r.difficulty ? ` · difficulty ${r.difficulty}` : ""}`,
    `- **You played:** ${r.humanSide}`,
    `- **Length:** ${r.moveCount} moves`,
    r.assisted ? "- **Hints were used in this game.**" : "",
  ]
    .filter(Boolean)
    .join("\n");
}

/** A full, self-contained brief for one reviewed game. */
export function buildGameBrief(r: GameRecord, review: GameReview): string {
  const lines: string[] = [header(r), ""];

  lines.push(`## How this was analysed`, "", review.method + ".", "");
  if (review.unavailable) lines.push(`> ${review.unavailable}`, "");

  lines.push(`## Summary`, "");
  lines.push(`- **Accuracy over your own moves:** ${review.accuracy}%`);
  const mine = review.moves.filter((m) => m.by !== "opponent");
  const bad = mine.filter((m) => m.label === "mistake" || m.label === "blunder");
  lines.push(`- **Your moves analysed:** ${mine.length}`);
  lines.push(`- **Mistakes and blunders:** ${bad.length}`);
  if (review.turningPointPly) {
    const t = review.moves.find((m) => m.ply === review.turningPointPly);
    lines.push(`- **Turning point:** move ${review.turningPointPly}${t ? ` (${t.text})` : ""}`);
  }
  lines.push("");

  if (review.moves.length > 0) {
    lines.push(`## Move by move`, "");
    lines.push(`| # | Side | Move | Verdict | Cost | Better |`);
    lines.push(`|---|------|------|---------|------|--------|`);
    for (const m of review.moves) {
      const side = m.by === "you" ? "you" : m.by === "solo" ? "—" : "opp";
      const cost = m.loss > 0 ? `${Math.round(m.loss * 100)}%` : "—";
      lines.push(
        `| ${m.ply} | ${side} | ${m.text} | ${LABEL_META[m.label].name} | ${cost} | ${m.best ?? "—"} |`
      );
    }
    lines.push("");
  }

  if (bad.length > 0) {
    lines.push(`## The moves worth talking about`, "");
    for (const m of bad.slice(0, 8)) {
      lines.push(
        `- **Move ${m.ply}, ${m.text}** — ${LABEL_META[m.label].name.toLowerCase()}, cost ${Math.round(
          m.loss * 100
        )}% of the position${m.best ? `; the analyser wanted ${m.best}` : ""}.${m.note ? ` ${m.note}` : ""}`
      );
    }
    lines.push("");
  }

  lines.push(
    `## What I'd like from you`,
    "",
    "1. Look past the individual moves: is there a *pattern* in the mistakes above — a phase of the game, a type of position, a piece I keep misusing?",
    "2. For the turning point, explain in words what I failed to see, and what I could have asked myself at the board that would have caught it.",
    "3. Give me one concrete thing to practise before my next game, and how I'd know it was working.",
    "",
    "_Generated by ChessRetabled. Analysis is from the app's own engine at review depth — treat the numbers as a guide, not gospel._"
  );

  return lines.join("\n");
}

/** A brief covering several games at once — for "what am I doing wrong lately". */
export function buildSessionBrief(items: { record: GameRecord; review: GameReview }[]): string {
  if (items.length === 0) return "# No games selected\n";
  const lines: string[] = [
    `# ${items.length} games for review`,
    "",
    `Games: ${items.map((i) => i.record.gameName).join(", ")}.`,
    "",
  ];
  const avg = Math.round(
    (items.reduce((a, i) => a + i.review.accuracy, 0) / items.length) * 10
  ) / 10;
  lines.push(`Average accuracy across these games: **${avg}%**.`, "");
  for (const i of items) {
    lines.push(`---`, "", buildGameBrief(i.record, i.review), "");
  }
  return lines.join("\n");
}

/** Save the brief next to wherever the user keeps their notes. */
export function downloadBrief(r: GameRecord, brief: string): void {
  const name = `${r.gameId}-${new Date(r.endedISO).toISOString().slice(0, 10)}-review.md`;
  const blob = new Blob([brief], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}
